import '../models/charger_model.dart';
import '../models/session_model.dart';

class MockData {
  static List<ChargerModel> getMockChargers() {
    return [
      ChargerModel(
        id: 'charger_001',
        name: 'Abu Dhabi Mall',
        address: 'Al Mina Road, Abu Dhabi',
        latitude: 24.4875,
        longitude: 54.3569,
        totalSockets: 8,
        availableSockets: 3,
        connectorTypes: ['Type 2', 'CCS'],
        pricesPerKwh: [1.25, 1.35],
        rating: 4.5,
        reviewCount: 142,
        hasParking: true,
        hasRestroom: true,
        operatingStatus: 'active',
      ),
      ChargerModel(
        id: 'charger_002',
        name: 'The Galleria Al Maryah Island',
        address: 'Al Maryah Island, Abu Dhabi',
        latitude: 24.5077,
        longitude: 54.4048,
        totalSockets: 10,
        availableSockets: 5,
        connectorTypes: ['Type 2', 'CCS', 'CHAdeMO'],
        pricesPerKwh: [1.30, 1.40, 1.45],
        rating: 4.7,
        reviewCount: 198,
        hasParking: true,
        hasRestroom: true,
        operatingStatus: 'active',
      ),
      ChargerModel(
        id: 'charger_003',
        name: 'Yas Mall',
        address: 'Yas Island, Abu Dhabi',
        latitude: 24.4883,
        longitude: 54.6071,
        totalSockets: 12,
        availableSockets: 8,
        connectorTypes: ['Type 2', 'CCS'],
        pricesPerKwh: [1.20, 1.32],
        rating: 4.6,
        reviewCount: 216,
        hasParking: true,
        hasRestroom: true,
        operatingStatus: 'active',
      ),
      ChargerModel(
        id: 'charger_004',
        name: 'Downtown Abu Dhabi',
        address: 'Sheikh Zayed Road, Abu Dhabi',
        latitude: 24.4269,
        longitude: 54.3618,
        totalSockets: 6,
        availableSockets: 2,
        connectorTypes: ['Type 2'],
        pricesPerKwh: [1.25],
        rating: 4.3,
        reviewCount: 89,
        hasParking: true,
        hasRestroom: false,
        operatingStatus: 'active',
      ),
      ChargerModel(
        id: 'charger_005',
        name: 'Dubai Mall',
        address: 'Downtown Dubai',
        latitude: 25.1972,
        longitude: 55.2744,
        totalSockets: 15,
        availableSockets: 7,
        connectorTypes: ['Type 2', 'CCS', 'CHAdeMO'],
        pricesPerKwh: [1.40, 1.50, 1.55],
        rating: 4.8,
        reviewCount: 342,
        hasParking: true,
        hasRestroom: true,
        operatingStatus: 'active',
      ),
      ChargerModel(
        id: 'charger_006',
        name: 'Mall of the Emirates',
        address: 'Sheikh Zayed Road, Dubai',
        latitude: 25.1186,
        longitude: 55.1976,
        totalSockets: 10,
        availableSockets: 4,
        connectorTypes: ['Type 2', 'CCS'],
        pricesPerKwh: [1.35, 1.45],
        rating: 4.5,
        reviewCount: 178,
        hasParking: true,
        hasRestroom: true,
        operatingStatus: 'active',
      ),
      ChargerModel(
        id: 'charger_007',
        name: 'Ibn Battuta Mall',
        address: 'Sheikh Zayed Road, Dubai',
        latitude: 25.0667,
        longitude: 55.0950,
        totalSockets: 8,
        availableSockets: 6,
        connectorTypes: ['Type 2'],
        pricesPerKwh: [1.28],
        rating: 4.4,
        reviewCount: 95,
        hasParking: true,
        hasRestroom: true,
        operatingStatus: 'active',
      ),
      ChargerModel(
        id: 'charger_008',
        name: 'Dubai Marina',
        address: 'Dubai Marina, Dubai',
        latitude: 25.0820,
        longitude: 55.1413,
        totalSockets: 12,
        availableSockets: 9,
        connectorTypes: ['Type 2', 'CCS'],
        pricesPerKwh: [1.45, 1.55],
        rating: 4.6,
        reviewCount: 201,
        hasParking: true,
        hasRestroom: true,
        operatingStatus: 'active',
      ),
      ChargerModel(
        id: 'charger_009',
        name: 'Jumeirah Beach Residence',
        address: 'Jumeirah, Dubai',
        latitude: 25.1356,
        longitude: 55.1507,
        totalSockets: 6,
        availableSockets: 3,
        connectorTypes: ['Type 2'],
        pricesPerKwh: [1.50],
        rating: 4.2,
        reviewCount: 67,
        hasParking: true,
        hasRestroom: false,
        operatingStatus: 'active',
      ),
      ChargerModel(
        id: 'charger_010',
        name: 'Emirates Mall',
        address: 'Muraqabat, Dubai',
        latitude: 25.2537,
        longitude: 55.3177,
        totalSockets: 10,
        availableSockets: 5,
        connectorTypes: ['Type 2', 'CCS'],
        pricesPerKwh: [1.32, 1.42],
        rating: 4.4,
        reviewCount: 134,
        hasParking: true,
        hasRestroom: true,
        operatingStatus: 'active',
      ),
      ChargerModel(
        id: 'charger_011',
        name: 'Al Wahda Mall',
        address: 'Abu Dhabi',
        latitude: 24.5245,
        longitude: 54.3638,
        totalSockets: 8,
        availableSockets: 4,
        connectorTypes: ['Type 2'],
        pricesPerKwh: [1.23],
        rating: 4.3,
        reviewCount: 102,
        hasParking: true,
        hasRestroom: true,
        operatingStatus: 'active',
      ),
      ChargerModel(
        id: 'charger_012',
        name: 'Al Reef Mall',
        address: 'Al Reef, Abu Dhabi',
        latitude: 24.5167,
        longitude: 54.2812,
        totalSockets: 9,
        availableSockets: 6,
        connectorTypes: ['Type 2', 'CCS'],
        pricesPerKwh: [1.26, 1.36],
        rating: 4.5,
        reviewCount: 118,
        hasParking: true,
        hasRestroom: true,
        operatingStatus: 'active',
      ),
    ];
  }

  static List<ChargingSession> getMockSessions() {
    final now = DateTime.now();
    return [
      ChargingSession(
        id: 'session_001',
        chargerId: 'charger_005',
        chargerName: 'Dubai Mall',
        userId: 'user_123',
        startTime: now.subtract(Duration(days: 1, hours: 2)),
        endTime: now.subtract(Duration(days: 1, hours: 1, minutes: 30)),
        energyDelivered: 28.5,
        costAed: 42.75,
        status: 'completed',
        socketNumber: 3,
      ),
      ChargingSession(
        id: 'session_002',
        chargerId: 'charger_003',
        chargerName: 'Yas Mall',
        userId: 'user_123',
        startTime: now.subtract(Duration(days: 3, hours: 4)),
        endTime: now.subtract(Duration(days: 3, hours: 3, minutes: 15)),
        energyDelivered: 35.0,
        costAed: 42.00,
        status: 'completed',
        socketNumber: 7,
      ),
      ChargingSession(
        id: 'session_003',
        chargerId: 'charger_001',
        chargerName: 'Abu Dhabi Mall',
        userId: 'user_123',
        startTime: now.subtract(Duration(days: 5, hours: 1)),
        endTime: now.subtract(Duration(days: 5, minutes: 45)),
        energyDelivered: 22.3,
        costAed: 27.88,
        status: 'completed',
        socketNumber: 2,
      ),
      ChargingSession(
        id: 'session_004',
        chargerId: 'charger_008',
        chargerName: 'Dubai Marina',
        userId: 'user_123',
        startTime: now.subtract(Duration(days: 7, hours: 2, minutes: 30)),
        endTime: now.subtract(Duration(days: 7, hours: 1, minutes: 50)),
        energyDelivered: 32.8,
        costAed: 50.88,
        status: 'completed',
        socketNumber: 5,
      ),
      ChargingSession(
        id: 'session_005',
        chargerId: 'charger_006',
        chargerName: 'Mall of the Emirates',
        userId: 'user_123',
        startTime: now.subtract(Duration(days: 9, hours: 3)),
        endTime: now.subtract(Duration(days: 9, hours: 2, minutes: 20)),
        energyDelivered: 40.0,
        costAed: 58.00,
        status: 'completed',
        socketNumber: 4,
      ),
      ChargingSession(
        id: 'session_006',
        chargerId: 'charger_002',
        chargerName: 'The Galleria Al Maryah Island',
        userId: 'user_123',
        startTime: now.subtract(Duration(days: 12, hours: 1, minutes: 45)),
        endTime: now.subtract(Duration(days: 12, hours: 1, minutes: 5)),
        energyDelivered: 25.6,
        costAed: 35.84,
        status: 'completed',
        socketNumber: 8,
      ),
      ChargingSession(
        id: 'session_007',
        chargerId: 'charger_010',
        chargerName: 'Emirates Mall',
        userId: 'user_123',
        startTime: now.subtract(Duration(days: 14, hours: 2, minutes: 15)),
        endTime: now.subtract(Duration(days: 14, hours: 1, minutes: 30)),
        energyDelivered: 31.2,
        costAed: 41.18,
        status: 'completed',
        socketNumber: 6,
      ),
      ChargingSession(
        id: 'session_008',
        chargerId: 'charger_011',
        chargerName: 'Al Wahda Mall',
        userId: 'user_123',
        startTime: now.subtract(Duration(days: 16, hours: 3)),
        endTime: now.subtract(Duration(days: 16, hours: 2, minutes: 25)),
        energyDelivered: 27.0,
        costAed: 33.21,
        status: 'completed',
        socketNumber: 1,
      ),
      ChargingSession(
        id: 'session_009',
        chargerId: 'charger_004',
        chargerName: 'Downtown Abu Dhabi',
        userId: 'user_123',
        startTime: now.subtract(Duration(days: 18, hours: 1, minutes: 50)),
        endTime: now.subtract(Duration(days: 18, hours: 1, minutes: 10)),
        energyDelivered: 19.5,
        costAed: 24.38,
        status: 'completed',
        socketNumber: 3,
      ),
      ChargingSession(
        id: 'session_010',
        chargerId: 'charger_012',
        chargerName: 'Al Reef Mall',
        userId: 'user_123',
        startTime: now.subtract(Duration(days: 20, hours: 2, minutes: 40)),
        endTime: now.subtract(Duration(days: 20, hours: 1, minutes: 55)),
        energyDelivered: 36.5,
        costAed: 46.44,
        status: 'completed',
        socketNumber: 9,
      ),
    ];
  }

  static SessionStats getMockSessionStats() {
    return SessionStats(
      totalSessions: 47,
      totalEnergyKwh: 1284.5,
      totalSpentAed: 1685.40,
      co2SavedKg: 641.2,
    );
  }
}
